---
title: "Introducción a la Ciencia de Datos"
subtitle: "Análisis de datos y algoritmos de predicción con R"
author: "Rafael A. Irizarry"
date: "`r Sys.Date()`"
documentclass: krantz
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
colorlinks: yes
lot: no
lof: no
graphics: yes
urlcolor: blue
geometry: "left=1.5in, right=1.5in, top=1.25in, bottom=1.25in"
description: Este libro presenta conceptos y destrezas que les ayudarán abordar los retos de situaciones actuales del análisis de datos. Cubre conceptos de probabilidad, inferencia estadística, regresión lineal y machine learning. Además, les permitirá desarrollar destrezas como la programación R, el wrangling de datos con dplyr, la visualización de datos con ggplot2, la organización de archivos con Shell de UNIX/ Linux, el control de versiones con GitHub y la preparación de documentos reproducibles con R markdown.
#documentclass: book
#classoption: openany
site: bookdown::bookdown_site
always_allow_html: yes
---


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
.packages(), 'bookdown', 'knitr', 'rmarkdown'), 'packages.bib')
```

# Prefácio {-}

Este livro começou como as notas usadas para ensinar a classe de
HarvardX [Data Science Series] (https://www.edx.org/professional-certificate/harvardx-data-science)^[https://www.edx.org/professional-certificate/harvardx-data-science].

O código Rmarkdown usado para gerar o livro está disponível em [GitHub] (https://github.com/rafalab/dsbook)^[https://github.com/rafalab/dsbook]. Observe que o tema gráfico usado para gráficos em todo o livro pode ser recriado usando a função `ds_theme_set()` do pacote __dslabs__.

Um PDF da versão em inglês deste livro está disponível em [Leanpub] (https://leanpub.com/datasciencebook)^[https://leanpub.com/datasciencebook].

Uma cópia impressa da versão em inglês deste livro está disponível em [CRC Press] (https://www.crcpress.com/Introduction-to-Data-Science-Data-Analysis-and-Prediction-Algorithms-with/Irizarry/ p/ book/ 9780367357986)^[https://www.crcpress.com/Introduction-to-Data-Science-Data-Analysis-and-Prediction-Algorithms-with/Irizarry/p/book/9780367357986].

Este trabalho foi publicado sob a licença Creative Commons Atribuição-Uso Não-Comercial-Compartilhamento pela mesma Licença 4.0 International [CC BY-NC-SA 4.0] (https://creativecommons.org/licenses/by-nc-sa/4.0).

Fazemos anúncios relacionados ao livro no Twitter. Para obter as informações mais recentes, siga [\@rafalab] (https://twitter.com/rafalab).

# Obrigado {-}

Este livro é dedicado a todos os envolvidos na construção e manutenção de pacotes R e R que usamos no texto. Um agradecimento especial aos desenvolvedores e mantenedores da base R, ao pacote _tidyverse_e__caret__.

Um agradecimento especial ao meu guru _tidyverse_ David Robinson e Amy Gill por dezenas de comentários, alterações e sugestões. Além disso, muito obrigado a Stephanie Hicks, que serviu duas vezes como co-instrutora em minhas aulas de ciência de dados, e a Yihui Xie, que pacientemente tolerou minhas múltiplas perguntas sobre livros. Agradeço também a Karl Broman, de quem pedi idéias emprestadas para as seções de visualização de dados e ferramentas de produtividade, e a Hector Corrada-Bravo, por seus conselhos sobre como melhor ensinar o aprendizado de máquinas. Agradeço a Peter Aldhous, de quem pedi idéias emprestadas para a seção sobre princípios de visualização de dados, e Jenny Bryan por escrever _Happy Git_e_GitHub pelo usoR_, que influenciou nossos capítulos do Git. Agradecemos a Alyssa Frazee por ajudar a criar o problema de lição de casa que se tornou o capítulo sobre sistemas de referência e a Amanda Cox por fornecer os dados do exame New York Regents. Além disso, muito obrigado a Jeff Leek, Roger Peng e Brian Caffo, cuja turma inspirou a forma como este livro é dividido, e Garrett Grolemund e Hadley Wickham por abrirem o código de reserva para seu livro R for Data Science. Finalmente, obrigado a Alex Nones por corrigir o manuscrito durante suas várias etapas.

Este livro foi concebido durante o ensino de vários cursos de estatística aplicada, iniciados há mais de quinze anos. Professores assistentes que trabalharam comigo ao longo dos anos fizeram importantes contribuições indiretas para este livro. A versão mais recente deste curso é uma série HarvardX coordenada por Heather Sternshein e Zofia Gajdos. Agradecemos suas contribuições. Também agradecemos a todos os alunos cujas perguntas e comentários nos ajudaram a melhorar o livro. Os cursos foram parcialmente financiados pelo subsídio NIH R25GM114818. Agradecemos aos Institutos Nacionais de Saúde por seu apoio.

Um agradecimento especial a todos aqueles que editaram o livro através de _pull request_do GitHub_ ou fizeram sugestões criando um _issue_ ou enviando um email: `nickyfoto` (Huang Qiang) `desautm` (Marc-André Désautels), `michaschwab` (Michail Schwab) `alvarolarreategui` (Alvaro Larreategui), `jakevc` (Jake VanCampen), `omerta` (Guillermo Lengemann), `espinielli` (Enrico Spinielli), `asimumba`(Aaron Simumba) `braunschweig` (Maldewar), `gwierzchowski` (Grzegorz Wierzchowski), `technocrat` (Richard Careaga) `atzakas`, `defeit` (David Emerson Feit), `shiraamitchell` (Shira Mitchell) `Nathalie-S`, `andreashandel` (Andreas Handel) `berkowitze` (Elias Berkowitz) `Dean-Webb` (Dean Webber), `mohayusuf`, `jimrothstein`, `mPloenzke` (Matthew Ploenzke), `NicholasDowand` (Nicholas Dow) `kant` (Darío Hereñú), `debbieyuster` (Debbie Yuster), `tuanchauict` (Tuan Chau), `phzeller`, David D. Kane, El Mustapha El Abbassi e Vadim Zipunnikov.

O livro foi traduzido para o espanhol por Alex Nones. Agradecemos a todos que contribuíram para esta tradução. Ilia Ushkin e Dustin Tingley geraram um primeiro rascunho usando um programa de tradução automática. Através do Twitter \@ R4DS_es e \@_lacion_ (Laura Ación), eles forneceram informações importantes sobre os recursos existentes. Vários outros contribuíram via Twitter, GitHub ou e-mail: \@hortizzuazaga (Humberto Ortiz), \@ribnikov (Jose Matestadístico), \@jarangoo (Julián A.), \@DiegoV_O_
(Diego), \@BrunoContrerasM (BContreras Moreira), \@ a2kimura (Alejandro Kimura), \@Emilio_NTN (Emilio García Morán), \@beto_bfr (betofogo), \@jdieramon (Jose V. Die), \yabellini ( Yanina Bellini Saibene), \@symusicicoup (Ismael Rudas), \@criztinaz (Cristina Zenteno), \@controlnegativo (Cristina de Dios), \@d_olivaw (Elio Campitelli), \@aguerri_jc (Jesús C. Aguerri), \@ pincheippie (Francisco, em casa) \@compBiology (Pedro Madrigal), \@RLadiesCuerna (RLadies Cuernavaca), \@thecarpentries, `eead-csic-compbio` (CSIC e Fundação ARAID), `pablormier` (Pablo R. Mier), `josschavezf` (Joselyn Chavez), `jmcastagnetto` (Jesus M. Castagnetto), `ismaelrudas`, `AnaBVA` (Ana B. Villaseñor Altamirano), @ pabloguti3rr3z (Pablo Gutierrez), Héctor Corrada-Bravo, Rafael A. Arce Nazario, Luis R. Pericchi Guerra, María E. Perez Hernández, Juan Carlos Perdomo, Anamari Irizarry e Amed Irizarry.





