# (PART) Estatísticas com R {-}

# Introdução à estatística com R

Análise de dados é um dos principais focos deste livro. Embora as ferramentas computacionais que introduzimos sejam desenvolvimentos relativamente recentes, a análise de dados existe há mais de um século. Ao longo dos anos, analistas de dados trabalhando em projetos específicos criaram ideias e conceitos que podem ser generalizados para muitas aplicações. Eles também identificaram formas comuns de ser enganado por padrões aparentes nos dados e por realidades matemáticas importantes que não são imediatamente óbvias. O acúmulo dessas ideias e percepções deu origem à disciplina da estatística, que oferece uma estrutura matemática para facilitar a descrição formal e a avaliação de tais ideias.

Para evitar repetir erros comuns e perder tempo reinventando a roda, é importante que os analistas de dados tenham um profundo entendimento de estatística. Entretanto, devido à maturidade da disciplina, existem dezenas de excelentes livros já publicados sobre esse assunto e, portanto, não nos concentramos em descrever a estrutura matemática aqui. Em vez disso, apresentamos brevemente conceitos e, em seguida, oferecemos estudos de caso que demonstram como as estatísticas são usadas na análise de dados, juntamente com o código em R que implementa essas ideias. Também usamos o código em R para ajudar a esclarecer alguns dos principais conceitos estatísticos geralmente descritos usando a matemática. Recomendamos fortemente complementar esta parte do livro com um manual básico de estatística. Dois exemplos são _Statistics_ de Freedman, Pisani e Purves e _Statistical Inference_ de Casella e Berger. Os conceitos específicos que discutimos nesta parte do livro são Probabilidade, Inferência Estatística, Modelos Estatísticos, Regressão e Modelos Lineares, que são os principais tópicos abordados em um curso de estatística. Os estudos de caso que apresentamos referem-se à crise financeira, previsão de resultados das eleições, entendendo a hereditariedade e como construir um time de beisebol.

